version: '2'
services:
  ds:
    working_dir: /home/ds/
    container_name: ds_container
    image: yaronv/ds
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - '~/python-envs/notebooks:/home/ds/notebooks/'
