version: '2'
services:
  ds_service:
    image: 'yaronv/ds:latest'
    working_dir: /home/ds/
    entrypoint: ./run_lab.sh
    stdin_open: true
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - '~/python-envs/notebooks:/home/ds/notebooks/'
